// <auto-generated />
namespace NomNom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class them_bang_taikhoan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_bang_taikhoan));
        
        string IMigrationMetadata.Id
        {
            get { return "201906132013074_them_bang_taikhoan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
