// <auto-generated />
namespace NomNom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class taobanggiohangs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taobanggiohangs));
        
        string IMigrationMetadata.Id
        {
            get { return "201906250411252_tao-bang-giohangs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
