// <auto-generated />
namespace NomNom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tao_bang_sanphams : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tao_bang_sanphams));
        
        string IMigrationMetadata.Id
        {
            get { return "201906140407311_tao_bang_sanphams"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
