// <auto-generated />
namespace NomNom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class capnhat_bang_donhangs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(capnhat_bang_donhangs));
        
        string IMigrationMetadata.Id
        {
            get { return "201906201830018_capnhat_bang_donhangs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
