// <auto-generated />
namespace NomNom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class them_bang_tintucs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_bang_tintucs));
        
        string IMigrationMetadata.Id
        {
            get { return "201906270928345_them_bang_tintucs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
