// <auto-generated />
namespace NomNom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cap_nhat_bang_taikhoans : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cap_nhat_bang_taikhoans));
        
        string IMigrationMetadata.Id
        {
            get { return "201906201757379_cap_nhat_bang_taikhoans"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
